"""add audience signals, evidence_ids on segments, current-profile index

Revision ID: 02b0466c5b7a
Revises: a83f3a112230
Create Date: 2026-09-08 11:22:49.035229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b0466c5b7a'
down_revision: Union[str, None] = 'a83f3a112230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_signals_creator_id'), 'audience_signals', ['creator_id'], unique=False)
    op.create_index('ux_audience_profiles_current', 'audience_profiles', ['creator_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.add_column('audience_segments', sa.Column('evidence_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audience_segments', 'evidence_ids')
    op.drop_index('ux_audience_profiles_current', table_name='audience_profiles', postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_audience_signals_creator_id'), table_name='audience_signals')
    op.drop_table('audience_signals')
    # ### end Alembic commands ###
