"""add trend_insights table

Revision ID: 081c622bc712
Revises: 11b611505d92
Create Date: 2026-09-11 11:57:51.504732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081c622bc712'
down_revision: Union[str, None] = '11b611505d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_key', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('recent_signal_count', sa.Integer(), nullable=False),
    sa.Column('momentum', sa.String(), nullable=False),
    sa.Column('saturation_estimate', sa.String(), nullable=True),
    sa.Column('durability', sa.String(), nullable=True),
    sa.Column('relevance_to_creator', sa.String(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('evidence_signal_ids', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id', 'topic_key', name='uq_trend_insights_creator_topic')
    )
    op.create_index(op.f('ix_trend_insights_creator_id'), 'trend_insights', ['creator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_insights_creator_id'), table_name='trend_insights')
    op.drop_table('trend_insights')
    # ### end Alembic commands ###
