"""add source_content_item_id to content_items

Revision ID: 11b611505d92
Revises: a3df3c490561
Create Date: 2026-09-11 10:55:26.443982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b611505d92'
down_revision: Union[str, None] = 'a3df3c490561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('source_content_item_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_content_items_source_content_item_id'), 'content_items', ['source_content_item_id'], unique=False)
    op.create_foreign_key(None, 'content_items', 'content_items', ['source_content_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_index(op.f('ix_content_items_source_content_item_id'), table_name='content_items')
    op.drop_column('content_items', 'source_content_item_id')
    # ### end Alembic commands ###
