"""add campaign_briefs table

Revision ID: 3a097019b81f
Revises: bbee0dbb0094
Create Date: 2026-09-10 15:45:12.099774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a097019b81f'
down_revision: Union[str, None] = 'bbee0dbb0094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_briefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_opportunity_id', sa.String(), nullable=False),
    sa.Column('objective_hypothesis', sa.Text(), nullable=True),
    sa.Column('campaign_concept', sa.Text(), nullable=True),
    sa.Column('content_format', sa.String(), nullable=True),
    sa.Column('why_this_brand', sa.Text(), nullable=True),
    sa.Column('why_now', sa.Text(), nullable=True),
    sa.Column('suggested_cta', sa.Text(), nullable=True),
    sa.Column('suggested_deliverables', sa.JSON(), nullable=True),
    sa.Column('pitch_angle', sa.Text(), nullable=True),
    sa.Column('personalization_facts', sa.JSON(), nullable=True),
    sa.Column('evidence_signal_ids', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_opportunity_id'], ['brand_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_opportunity_id', name='uq_campaign_briefs_brand_opportunity')
    )
    op.create_index(op.f('ix_campaign_briefs_brand_opportunity_id'), 'campaign_briefs', ['brand_opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_briefs_brand_opportunity_id'), table_name='campaign_briefs')
    op.drop_table('campaign_briefs')
    # ### end Alembic commands ###
