"""add commercial_profiles table

Revision ID: 6b1cd80bf42b
Revises: 073e87365830
Create Date: 2026-09-09 23:17:01.880873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1cd80bf42b'
down_revision: Union[str, None] = '073e87365830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('ideal_sponsor_categories', sa.JSON(), nullable=True),
    sa.Column('prohibited_categories', sa.JSON(), nullable=True),
    sa.Column('target_geographies', sa.JSON(), nullable=True),
    sa.Column('preferred_deal_formats', sa.JSON(), nullable=True),
    sa.Column('minimum_conditions', sa.Text(), nullable=True),
    sa.Column('exclusivity_constraints', sa.Text(), nullable=True),
    sa.Column('usage_rights_preferences', sa.Text(), nullable=True),
    sa.Column('sponsorship_goals', sa.Text(), nullable=True),
    sa.Column('revenue_goal', sa.Text(), nullable=True),
    sa.Column('brands_to_avoid', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_profiles_creator_id'), 'commercial_profiles', ['creator_id'], unique=False)
    op.create_index('ux_commercial_profiles_current', 'commercial_profiles', ['creator_id'], unique=True, postgresql_where=sa.text('is_current'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_commercial_profiles_current', table_name='commercial_profiles', postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_commercial_profiles_creator_id'), table_name='commercial_profiles')
    op.drop_table('commercial_profiles')
    # ### end Alembic commands ###
