"""add unique current voice profile index

Revision ID: 709ca6abefe4
Revises: d763b67d7c90
Create Date: 2026-09-08 08:48:34.209227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709ca6abefe4'
down_revision: Union[str, None] = 'd763b67d7c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ux_voice_profiles_current', 'voice_profiles', ['creator_id'], unique=True, postgresql_where=sa.text('is_current'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_voice_profiles_current', table_name='voice_profiles', postgresql_where=sa.text('is_current'))
    # ### end Alembic commands ###
