"""add outreach_threads and outreach_messages tables

Revision ID: a3df3c490561
Revises: 3a097019b81f
Create Date: 2026-09-10 20:06:05.810047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3df3c490561'
down_revision: Union[str, None] = '3a097019b81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_opportunity_id', sa.String(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('campaign_brief_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('creator_decision', sa.String(), nullable=True),
    sa.Column('creator_decision_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deal_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brand_opportunity_id'], ['brand_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_brief_id'], ['campaign_briefs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['brand_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_threads_brand_opportunity_id'), 'outreach_threads', ['brand_opportunity_id'], unique=False)
    op.create_index(op.f('ix_outreach_threads_creator_id'), 'outreach_threads', ['creator_id'], unique=False)
    op.create_table('outreach_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['outreach_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_messages_thread_id'), 'outreach_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_messages_thread_id'), table_name='outreach_messages')
    op.drop_table('outreach_messages')
    op.drop_index(op.f('ix_outreach_threads_creator_id'), table_name='outreach_threads')
    op.drop_index(op.f('ix_outreach_threads_brand_opportunity_id'), table_name='outreach_threads')
    op.drop_table('outreach_threads')
    # ### end Alembic commands ###
