"""add confidence to strategies

Revision ID: a83f3a112230
Revises: 709ca6abefe4
Create Date: 2026-09-08 10:57:58.702675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83f3a112230'
down_revision: Union[str, None] = '709ca6abefe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'confidence')
    # ### end Alembic commands ###
