"""add brand_opportunities table

Revision ID: b3c97527d42c
Revises: b1e91650b180
Create Date: 2026-09-10 10:23:24.833962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c97527d42c'
down_revision: Union[str, None] = 'b1e91650b180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_components', sa.JSON(), nullable=True),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('evidence_signal_ids', sa.JSON(), nullable=True),
    sa.Column('suggested_contact_roles', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', name='uq_brand_opportunities_brand')
    )
    op.create_index(op.f('ix_brand_opportunities_brand_id'), 'brand_opportunities', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_opportunities_creator_id'), 'brand_opportunities', ['creator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_opportunities_creator_id'), table_name='brand_opportunities')
    op.drop_index(op.f('ix_brand_opportunities_brand_id'), table_name='brand_opportunities')
    op.drop_table('brand_opportunities')
    # ### end Alembic commands ###
