"""add prohibited_conflict to brand_opportunities

Revision ID: bbee0dbb0094
Revises: b3c97527d42c
Create Date: 2026-09-10 15:14:53.063023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbee0dbb0094'
down_revision: Union[str, None] = 'b3c97527d42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so this NOT NULL column can land on a table that may
    # already have rows (every pre-existing BrandOpportunity had no conflict
    # signal computed, so False is the correct backfill, not just a
    # migration convenience).
    op.add_column(
        'brand_opportunities',
        sa.Column('prohibited_conflict', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('brand_opportunities', 'prohibited_conflict', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand_opportunities', 'prohibited_conflict')
    # ### end Alembic commands ###
