"""initial schema

Revision ID: bc4c72b5fb68
Revises: 
Create Date: 2026-09-07 22:17:57.848894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bc4c72b5fb68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source_title', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('evidence_quality', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('supabase_auth_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supabase_auth_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('creators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('niche', sa.String(), nullable=True),
    sa.Column('sub_niche', sa.String(), nullable=True),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('business_model', sa.String(), nullable=True),
    sa.Column('monetization_model', sa.String(), nullable=True),
    sa.Column('onboarding_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_user_id'), 'creators', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('state_changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_creator_id'), 'agent_runs', ['creator_id'], unique=False)
    op.create_table('audience_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('geography', sa.JSON(), nullable=True),
    sa.Column('demographics', sa.JSON(), nullable=True),
    sa.Column('psychographics', sa.JSON(), nullable=True),
    sa.Column('knowledge_level', sa.String(), nullable=True),
    sa.Column('purchase_intent', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_profiles_creator_id'), 'audience_profiles', ['creator_id'], unique=False)
    op.create_table('audience_segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('problems', sa.JSON(), nullable=True),
    sa.Column('desires', sa.JSON(), nullable=True),
    sa.Column('objections', sa.JSON(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('fears', sa.JSON(), nullable=True),
    sa.Column('aspirations', sa.JSON(), nullable=True),
    sa.Column('language', sa.JSON(), nullable=True),
    sa.Column('knowledge_level', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_segments_creator_id'), 'audience_segments', ['creator_id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_creator_id'), 'competitors', ['creator_id'], unique=False)
    op.create_table('content_pillars',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_pillars_creator_id'), 'content_pillars', ['creator_id'], unique=False)
    op.create_table('creator_goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_metric', sa.String(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_goals_creator_id'), 'creator_goals', ['creator_id'], unique=False)
    op.create_table('creator_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_preferences_creator_id'), 'creator_preferences', ['creator_id'], unique=False)
    op.create_table('creator_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('expertise', sa.JSON(), nullable=True),
    sa.Column('positioning_statement', sa.Text(), nullable=True),
    sa.Column('prohibited_topics', sa.JSON(), nullable=True),
    sa.Column('avoided_claims', sa.JSON(), nullable=True),
    sa.Column('rejected_tones', sa.JSON(), nullable=True),
    sa.Column('disclosure_requirements', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_profiles_creator_id'), 'creator_profiles', ['creator_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('variable', sa.String(), nullable=True),
    sa.Column('control_reference', sa.Text(), nullable=True),
    sa.Column('planned_test_set', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_creator_id'), 'experiments', ['creator_id'], unique=False)
    op.create_table('research_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('subtopic', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('engagement', sa.JSON(), nullable=True),
    sa.Column('content_features', sa.JSON(), nullable=True),
    sa.Column('audience_signals', sa.JSON(), nullable=True),
    sa.Column('hook_type', sa.String(), nullable=True),
    sa.Column('topic_cluster', sa.String(), nullable=True),
    sa.Column('evidence_quality', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_signals_creator_id'), 'research_signals', ['creator_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_account_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_accounts_creator_id'), 'social_accounts', ['creator_id'], unique=False)
    op.create_table('strategic_learnings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategic_learnings_creator_id'), 'strategic_learnings', ['creator_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_creator_id'), 'strategies', ['creator_id'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('vocabulary', sa.JSON(), nullable=True),
    sa.Column('sentence_style', sa.String(), nullable=True),
    sa.Column('pacing', sa.String(), nullable=True),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('humor_level', sa.String(), nullable=True),
    sa.Column('controversy_tolerance', sa.String(), nullable=True),
    sa.Column('storytelling_style', sa.String(), nullable=True),
    sa.Column('opinion_style', sa.String(), nullable=True),
    sa.Column('signature_phrases', sa.JSON(), nullable=True),
    sa.Column('cta_style', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_creator_id'), 'voice_profiles', ['creator_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_agent_run_id'), 'agent_messages', ['agent_run_id'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tool_calls_agent_run_id'), 'agent_tool_calls', ['agent_run_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('subtopic', sa.String(), nullable=True),
    sa.Column('angle', sa.Text(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('audience_segment_id', sa.String(), nullable=True),
    sa.Column('content_pillar_id', sa.String(), nullable=True),
    sa.Column('strategic_goal', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_components', sa.JSON(), nullable=True),
    sa.Column('competition_level', sa.String(), nullable=True),
    sa.Column('saturation_estimate', sa.String(), nullable=True),
    sa.Column('production_complexity', sa.String(), nullable=True),
    sa.Column('recommended_time_window', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['audience_segment_id'], ['audience_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_pillar_id'], ['content_pillars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_creator_id'), 'opportunities', ['creator_id'], unique=False)
    op.create_table('state_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_for_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_for_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_snapshots_creator_id'), 'state_snapshots', ['creator_id'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pillar_id', sa.String(), nullable=True),
    sa.Column('opportunity_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pillar_id'], ['content_pillars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_creator_id'), 'content_items', ['creator_id'], unique=False)
    op.create_table('strategy_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('portfolio_role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_items_strategy_id'), 'strategy_items', ['strategy_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_creator_id'), 'calendar_events', ['creator_id'], unique=False)
    op.create_table('content_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('storage_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assets_content_item_id'), 'content_assets', ['content_item_id'], unique=False)
    op.create_table('content_briefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('audience_segment_id', sa.String(), nullable=True),
    sa.Column('core_insight', sa.Text(), nullable=True),
    sa.Column('angle', sa.Text(), nullable=True),
    sa.Column('hook_type', sa.String(), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('narrative_structure', sa.JSON(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('broll_suggestions', sa.JSON(), nullable=True),
    sa.Column('on_screen_text', sa.JSON(), nullable=True),
    sa.Column('pacing', sa.String(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('caption_concept', sa.Text(), nullable=True),
    sa.Column('cover_concept', sa.Text(), nullable=True),
    sa.Column('repurposing_opportunities', sa.JSON(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audience_segment_id'], ['audience_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_briefs_content_item_id'), 'content_briefs', ['content_item_id'], unique=False)
    op.create_table('content_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_embeddings_creator_id'), 'content_embeddings', ['creator_id'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_versions_content_item_id'), 'content_versions', ['content_item_id'], unique=False)
    op.create_table('experiment_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_results_experiment_id'), 'experiment_results', ['experiment_id'], unique=False)
    op.create_table('opportunity_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('research_signal_id', sa.String(), nullable=True),
    sa.Column('content_item_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_signal_id'], ['research_signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_evidence_opportunity_id'), 'opportunity_evidence', ['opportunity_id'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_content_item_id'), 'performance_metrics', ['content_item_id'], unique=False)
    op.create_table('performance_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('watch_time', sa.Float(), nullable=True),
    sa.Column('avg_view_duration', sa.Float(), nullable=True),
    sa.Column('retention', sa.Float(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('followers_gained', sa.Integer(), nullable=True),
    sa.Column('profile_visits', sa.Integer(), nullable=True),
    sa.Column('baseline_comparison', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_content_item_id'), 'performance_snapshots', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_creator_id'), 'performance_snapshots', ['creator_id'], unique=False)
    op.create_table('published_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_content_content_item_id'), 'published_content', ['content_item_id'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=False),
    sa.Column('brief_id', sa.String(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('hook_variants', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('critic_score', sa.Integer(), nullable=True),
    sa.Column('critic_issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['content_briefs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_content_item_id'), 'scripts', ['content_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scripts_content_item_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_published_content_content_item_id'), table_name='published_content')
    op.drop_table('published_content')
    op.drop_index(op.f('ix_performance_snapshots_creator_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_content_item_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_performance_metrics_content_item_id'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_opportunity_evidence_opportunity_id'), table_name='opportunity_evidence')
    op.drop_table('opportunity_evidence')
    op.drop_index(op.f('ix_experiment_results_experiment_id'), table_name='experiment_results')
    op.drop_table('experiment_results')
    op.drop_index(op.f('ix_content_versions_content_item_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_content_embeddings_creator_id'), table_name='content_embeddings')
    op.drop_table('content_embeddings')
    op.drop_index(op.f('ix_content_briefs_content_item_id'), table_name='content_briefs')
    op.drop_table('content_briefs')
    op.drop_index(op.f('ix_content_assets_content_item_id'), table_name='content_assets')
    op.drop_table('content_assets')
    op.drop_index(op.f('ix_calendar_events_creator_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_strategy_items_strategy_id'), table_name='strategy_items')
    op.drop_table('strategy_items')
    op.drop_index(op.f('ix_content_items_creator_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_state_snapshots_creator_id'), table_name='state_snapshots')
    op.drop_table('state_snapshots')
    op.drop_index(op.f('ix_opportunities_creator_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_agent_tool_calls_agent_run_id'), table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index(op.f('ix_agent_messages_agent_run_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_voice_profiles_creator_id'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_strategies_creator_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_strategic_learnings_creator_id'), table_name='strategic_learnings')
    op.drop_table('strategic_learnings')
    op.drop_index(op.f('ix_social_accounts_creator_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_research_signals_creator_id'), table_name='research_signals')
    op.drop_table('research_signals')
    op.drop_index(op.f('ix_experiments_creator_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_creator_profiles_creator_id'), table_name='creator_profiles')
    op.drop_table('creator_profiles')
    op.drop_index(op.f('ix_creator_preferences_creator_id'), table_name='creator_preferences')
    op.drop_table('creator_preferences')
    op.drop_index(op.f('ix_creator_goals_creator_id'), table_name='creator_goals')
    op.drop_table('creator_goals')
    op.drop_index(op.f('ix_content_pillars_creator_id'), table_name='content_pillars')
    op.drop_table('content_pillars')
    op.drop_index(op.f('ix_competitors_creator_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_audience_segments_creator_id'), table_name='audience_segments')
    op.drop_table('audience_segments')
    op.drop_index(op.f('ix_audience_profiles_creator_id'), table_name='audience_profiles')
    op.drop_table('audience_profiles')
    op.drop_index(op.f('ix_agent_runs_creator_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_creators_user_id'), table_name='creators')
    op.drop_table('creators')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('research_sources')
    # ### end Alembic commands ###
