"""add unique current creator profile index

Revision ID: d763b67d7c90
Revises: bc4c72b5fb68
Create Date: 2026-09-07 22:52:18.572592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd763b67d7c90'
down_revision: Union[str, None] = 'bc4c72b5fb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ux_creator_profiles_current', 'creator_profiles', ['creator_id'], unique=True, postgresql_where=sa.text('is_current'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_creator_profiles_current', table_name='creator_profiles', postgresql_where=sa.text('is_current'))
    # ### end Alembic commands ###
